import React from 'react';
import ReactMarkdown from 'react-markdown';
import { Copy, FileDown, FileText, Printer, BookOpen, Clock } from 'lucide-react';
import toast from 'react-hot-toast';

interface ReportViewerProps {
  reportText: string;
  topic: string;
}

export const ReportViewer: React.FC<ReportViewerProps> = ({ reportText, topic }) => {
  if (!reportText) return null;

  const wordCount = reportText.trim().split(/\s+/).filter(Boolean).length;
  const readingTime = Math.ceil(wordCount / 200); // average 200 wpm

  const handleCopy = () => {
    navigator.clipboard.writeText(reportText);
    toast.success('Report copied to clipboard');
  };

  const handleDownloadMarkdown = () => {
    const blob = new Blob([reportText], { type: 'text/markdown;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.setAttribute('download', `DeepScout_Report_${topic.replace(/\s+/g, '_')}.md`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    toast.success('Markdown report downloaded');
  };

  const handleDownloadPDF = () => {
    // Elegant client-side PDF export via printing
    const printWindow = window.open('', '_blank');
    if (!printWindow) {
      toast.error('Pop-up blocked. Please allow pop-ups for PDF generation.');
      return;
    }
    
    const styledHtml = `
      <html>
        <head>
          <title>${topic} - DeepScout Research Report</title>
          <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css">
          <style>
            body { font-family: system-ui, sans-serif; color: #111827; padding: 40px; }
            h1 { font-size: 2.25rem; font-weight: 800; margin-bottom: 1.5rem; border-bottom: 2px solid #E5E7EB; padding-bottom: 0.5rem; }
            h2 { font-size: 1.5rem; font-weight: 700; margin-top: 2rem; margin-bottom: 1rem; color: #1F2937; }
            h3 { font-size: 1.25rem; font-weight: 600; margin-top: 1.5rem; margin-bottom: 0.75rem; }
            p { margin-bottom: 1.25rem; line-height: 1.625; }
            ul, ol { margin-left: 1.5rem; margin-bottom: 1.25rem; }
            li { margin-bottom: 0.5rem; }
            blockquote { border-left: 4px solid #3B82F6; padding-left: 1rem; color: #4B5563; font-style: italic; margin: 1.5rem 0; }
            table { width: 100%; border-collapse: collapse; margin-bottom: 1.5rem; }
            th, td { border: 1px solid #E5E7EB; padding: 0.75rem; text-align: left; }
            th { background-color: #F9FAFB; font-weight: 600; }
            pre, code { font-family: monospace; background-color: #F3F4F6; padding: 0.2rem 0.4rem; border-radius: 4px; font-size: 0.875rem; }
            pre { padding: 1rem; overflow-x: auto; margin-bottom: 1.5rem; }
            .header-info { color: #6B7280; font-size: 0.875rem; margin-bottom: 2rem; }
          </style>
        </head>
        <body>
          <h1>${topic}</h1>
          <div class="header-info">
            Generated by DeepScout AI Autonomous Research Agent | Reading Time: ${readingTime} min (${wordCount} words)
          </div>
          <div id="content"></div>
          <script src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"></script>
          <script>
            document.getElementById('content').innerHTML = marked.parse(\`${reportText.replace(/`/g, '\\`').replace(/\$/g, '\\$')}\`);
            setTimeout(() => {
              window.print();
              window.close();
            }, 500);
          </script>
        </body>
      </html>
    `;
    
    printWindow.document.write(styledHtml);
    printWindow.document.close();
  };

  const handleExportDocx = () => {
    // Export raw HTML directly to docx/doc format (Word matches this format nicely)
    const header = `<html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:w='urn:schemas-microsoft-com:office:word' xmlns='http://www.w3.org/TR/REC-html40'>
    <head><title>${topic}</title><style>body {font-family: Arial;}</style></head>
    <body><h1>${topic}</h1>`;
    const footer = '</body></html>';
    
    // We convert markdown to html simply using a browser-friendly fallback or simple markdown-like HTML output
    const mockHtml = reportText
      .replace(/^### (.*$)/gim, '<h3>$1</h3>')
      .replace(/^## (.*$)/gim, '<h2>$1</h2>')
      .replace(/^# (.*$)/gim, '<h1>$1</h1>')
      .replace(/^\* (.*$)/gim, '<ul><li>$1</li></ul>')
      .replace(/^- (.*$)/gim, '<ul><li>$1</li></ul>')
      .replace(/\n\n/g, '<p></p>');

    const doc = header + mockHtml + footer;
    const blob = new Blob([doc], { type: 'application/msword' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.setAttribute('download', `DeepScout_Report_${topic.replace(/\s+/g, '_')}.doc`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    toast.success('Word Document exported');
  };

  return (
    <div className="w-full max-w-4xl mx-auto px-6 py-6 relative z-10 text-left">
      <div className="glass-panel border border-white/10 rounded-3xl overflow-hidden shadow-2xl">
        {/* Top Info Bar */}
        <div className="bg-white/5 px-6 py-4 flex flex-wrap items-center justify-between gap-4 border-b border-white/5">
          <div className="flex items-center gap-6 text-xs text-gray-400">
            <div className="flex items-center gap-1.5">
              <Clock className="w-4 h-4 text-brand-primary" />
              <span>{readingTime} min read</span>
            </div>
            <div className="flex items-center gap-1.5">
              <BookOpen className="w-4 h-4 text-brand-secondary" />
              <span>{wordCount} words</span>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={handleCopy}
              className="p-2 hover:bg-white/5 rounded-lg border border-white/5 text-gray-300 hover:text-white transition flex items-center gap-1.5 text-xs cursor-pointer"
            >
              <Copy className="w-3.5 h-3.5" />
              <span>Copy</span>
            </button>
            <button
              onClick={handleDownloadMarkdown}
              className="p-2 hover:bg-white/5 rounded-lg border border-white/5 text-gray-300 hover:text-white transition flex items-center gap-1.5 text-xs cursor-pointer"
            >
              <FileDown className="w-3.5 h-3.5" />
              <span>MD</span>
            </button>
            <button
              onClick={handleDownloadPDF}
              className="p-2 hover:bg-white/5 rounded-lg border border-white/5 text-gray-300 hover:text-white transition flex items-center gap-1.5 text-xs cursor-pointer"
            >
              <Printer className="w-3.5 h-3.5" />
              <span>PDF</span>
            </button>
            <button
              onClick={handleExportDocx}
              className="p-2 hover:bg-white/5 rounded-lg border border-white/5 text-gray-300 hover:text-white transition flex items-center gap-1.5 text-xs cursor-pointer"
            >
              <FileText className="w-3.5 h-3.5" />
              <span>Word</span>
            </button>
          </div>
        </div>

        {/* Markdown Reader Body */}
        <div className="p-8 md:p-12 text-gray-200 prose prose-invert max-w-none prose-headings:text-white prose-a:text-brand-primary prose-strong:text-white prose-table:border-collapse prose-th:border prose-th:border-white/10 prose-th:p-3 prose-td:border prose-td:border-white/10 prose-td:p-3 font-light leading-relaxed tracking-wide text-sm md:text-base">
          <ReactMarkdown
            components={{
              code({ className, children }) {
                const match = /language-(\w+)/.exec(className || '');
                return match ? (
                  <div className="my-4 rounded-xl overflow-hidden border border-white/10 bg-black/60 p-4">
                    <pre className="font-mono text-xs md:text-sm text-gray-300 overflow-x-auto leading-relaxed">
                      <code>{String(children).replace(/\n$/, '')}</code>
                    </pre>
                  </div>
                ) : (
                  <code className="bg-white/5 px-1.5 py-0.5 rounded font-mono text-brand-primary text-xs">
                    {children}
                  </code>
                );
              },
              h1: ({ children }) => <h1 className="text-3xl font-bold text-white border-b border-white/10 pb-3 mb-6 mt-8">{children}</h1>,
              h2: ({ children }) => <h2 className="text-2xl font-bold text-white mt-8 mb-4">{children}</h2>,
              h3: ({ children }) => <h3 className="text-xl font-semibold text-white mt-6 mb-3">{children}</h3>,
              p: ({ children }) => <p className="mb-4 text-gray-300">{children}</p>,
              ul: ({ children }) => <ul className="list-disc pl-6 mb-4 space-y-2 text-gray-300">{children}</ul>,
              ol: ({ children }) => <ol className="list-decimal pl-6 mb-4 space-y-2 text-gray-300">{children}</ol>,
              blockquote: ({ children }) => <blockquote className="border-l-4 border-brand-primary pl-4 py-1 my-4 bg-white/5 rounded-r italic text-gray-400">{children}</blockquote>,
            }}
          >
            {reportText}
          </ReactMarkdown>
        </div>
      </div>
    </div>
  );
};
